### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/subject-id-gen#2]
Why do some styles have `scss` extention?

https://github.com/PREDICT-DPACC/subject-id-gen/tree/main/src/styles

**Comment by blms** [comment]
`scss` is the extension for [SASS](https://sass-lang.com/). I started out using plain CSS, but at a certain point I wanted to use some SASS syntax, so I installed it and started using SASS modules from then on. An example of SASS syntax is the nesting as seen in `Table.module.scss` and `/components/Admin/AdminNav/AdminNav.module.scss`.

For consistency they could all be renamed `scss`. I did not bother since it's not strictly necessary.

**Comment by tashrifbillah** [comment]
Although I have an admin email in `.env.local`, must I register here again?

![image](https://user-images.githubusercontent.com/35086881/123171538-f4d17180-d449-11eb-8409-34d44e2a66f3.png)


P.S. the admin email and mongo user passport does not work here.

**Comment by blms** [comment]
Yes, you need to register there and supply a new password for the web UI. It's different from the Mongo user/pass—that's only ever used in the connection string.

BTW, this will also require SMTP to be configured properly, because it requires the admin email to be verified. I haven't tested it with local SMTP, only remote (SendGrid free tier service). So using a local SMTP server may not work without modification.

If the email verification doesn't send properly, and you just want to test the rest of the app without email stuff configured, you can do this in the MongoDB shell:
```
db.users.findOneAndUpdate({ "email": <YourEmail> }, { $set: { "role": "admin", "isVerified": true } })
```

If you do want to try modifying the code to get local SMTP working, the [relevant code is here](https://github.com/PREDICT-DPACC/subject-id-gen/blob/e86806feb56dc073ca5cc85c5b1bdcc1bd9b8203/src/lib/mail.js#L11-L20) and the [nodemailer docs are here](https://nodemailer.com/smtp/).

**Comment by tashrifbillah** [comment]
> I haven't tested it with local SMTP

Working fine, I have reported in #3 yersterday. Thanks.

**Comment by tashrifbillah** [comment]
Graning access site-by-site seems too much work on the UI when I requested access to all 42 of them. Is there a mongo code we can run more conveniently to grant access?

**Comment by blms** [comment]
> Graning access site-by-site seems too much work on the UI when I requested access to all 42 of them. Is there a mongo code we can run more conveniently to grant access?

You may try going to Administration --> Users --> Make Site Manager to grant site management access to all of them. There's no convenient way right now to make someone just a member and not a manager, so if you want to do that you'd have to go the Administration --> Sites and change them site by site.

In MongoDB, if you do `db.users.findOne()` you can get a sense of what you'd have to do to grant access quickly:
```
{
...
	"requestedSites" : [
		"CP",
		"PI",
		"TE"
	],
	"access" : [
		{
			"siteId" : "AD",
			"siteRole" : "manager"
		},
		{
			"siteId" : "AM",
			"siteRole" : "manager"
		},
...
}
```

You would have to do something like
```
db.usres.findOneAndUpdate({
  "email": <email>
},
{ 
  $push: {
    "access": { $each: [
        {
          "siteId": "CP",
          "siteRole": "member"
        },
        {
          "siteId": "PI",
          "siteRole": "member"
        }
      ]
    }
  }, 
  $pull: {
    "requestedSites": { $in: [
        "CP",
        "PI"
      ]
    }
  }
})
```

**Comment by tashrifbillah** [comment]
> if you do db.users.findOne() you can get a sense of what you'd have to do

Sure.
